/homes/benjaminv/programs/miniconda/lib/python3.7/runpy.py:125: RuntimeWarning: 'gridmap.runner' found in sys.modules after import of package 'gridmap', but prior to execution of 'gridmap.runner'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
2019-03-12 19:38:32,962 - __main__ - INFO - Appended /homes/benjaminv/Code/ferromtm/ferromtm/models to PYTHONPATH
2019-03-12 19:38:32,963 - __main__ - INFO - Starting heart beat
2019-03-12 19:38:32,967 - __main__ - INFO - Waiting 1 seconds before fetching input
2019-03-12 19:38:39,986 - __main__ - ERROR - Could not retrieve input for job 356212
Traceback (most recent call last):
  File "/homes/benjaminv/programs/miniconda/lib/python3.7/site-packages/gridmap/runner.py", line 204, in _run_job
    job = _send_zmq_msg(job_id, "fetch_input", None, address)
  File "/homes/benjaminv/programs/miniconda/lib/python3.7/site-packages/gridmap/runner.py", line 87, in _send_zmq_msg
    msg = zloads(zsocket.recv())
  File "/homes/benjaminv/programs/miniconda/lib/python3.7/site-packages/gridmap/data.py", line 63, in zloads
    return pickle.loads(bz2.decompress(pickled_data))
  File "/homes/benjaminv/Code/ferromtm/ferromtm/models/slab.py", line 80, in <module>
    mesh = fem.make_mesh()
  File "/homes/benjaminv/Code/pytheas/pytheas/basefem/basefem.py", line 306, in make_mesh
    self.nodes, self.els, self.des = self.get_mesh_info()
  File "/homes/benjaminv/Code/pytheas/pytheas/basefem/basefem.py", line 443, in get_mesh_info
    nodes = self.get_design_nodes()
  File "/homes/benjaminv/Code/pytheas/pytheas/basefem/basefem.py", line 270, in get_design_nodes
    return femio.get_nodes(self.path_mesh, self.dom_des, self.celltype)
  File "/homes/benjaminv/Code/pytheas/pytheas/tools/femio.py", line 138, in get_nodes
    mesh = meshio.read(path_mesh)
  File "/homes/benjaminv/programs/miniconda/lib/python3.7/site-packages/meshio/helpers.py", line 174, in read
    return format_to_reader[file_format].read(filename)
  File "/homes/benjaminv/programs/miniconda/lib/python3.7/site-packages/meshio/msh_io/main.py", line 12, in read
    mesh = read_buffer(f)
  File "/homes/benjaminv/programs/miniconda/lib/python3.7/site-packages/meshio/msh_io/main.py", line 31, in read_buffer
    return reader.read_buffer(f, is_ascii, int_size, data_size)
  File "/homes/benjaminv/programs/miniconda/lib/python3.7/site-packages/meshio/msh_io/msh2.py", line 50, in read_buffer
    points = _read_nodes(f, is_ascii, int_size, data_size)
  File "/homes/benjaminv/programs/miniconda/lib/python3.7/site-packages/meshio/msh_io/msh2.py", line 91, in _read_nodes
    points = numpy.fromfile(f, count=num_nodes * 4, sep=" ").reshape((num_nodes, 4))
ValueError: cannot reshape array of size 0 into shape (5476,4)
